namespace DimStock.Screens
{
    partial class UserLoginAddScreen
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UserLoginAddScreen));
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            this.TextYourName = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.TextEmail = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.TextLogin = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.TextAccessPassWord = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.TextPassWordCheck = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForm.BunifuShadowPanel.BunifuShadowPanel();
            this.bunifuShadowPanel2 = new Bunifu.UI.WinForm.BunifuShadowPanel.BunifuShadowPanel();
            this.ButtonClose = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ButtonClearView = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ButtonDelete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ButtonSave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuShadowPanel3 = new Bunifu.UI.WinForm.BunifuShadowPanel.BunifuShadowPanel();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuShadowPanel1.SuspendLayout();
            this.bunifuShadowPanel2.SuspendLayout();
            this.bunifuShadowPanel3.SuspendLayout();
            this.SuspendLayout();
            // 
            // TextYourName
            // 
            this.TextYourName.AcceptsReturn = false;
            this.TextYourName.AcceptsTab = false;
            this.TextYourName.AnimationSpeed = 200;
            this.TextYourName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextYourName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextYourName.BackColor = System.Drawing.Color.Transparent;
            this.TextYourName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextYourName.BackgroundImage")));
            this.TextYourName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextYourName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextYourName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextYourName.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextYourName.BorderRadius = 1;
            this.TextYourName.BorderThickness = 1;
            this.TextYourName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextYourName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextYourName.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextYourName.DefaultText = "";
            this.TextYourName.FillColor = System.Drawing.Color.White;
            this.TextYourName.HideSelection = true;
            this.TextYourName.IconLeft = null;
            this.TextYourName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextYourName.IconPadding = 10;
            this.TextYourName.IconRight = null;
            this.TextYourName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextYourName.Lines = new string[0];
            this.TextYourName.Location = new System.Drawing.Point(27, 68);
            this.TextYourName.MaxLength = 32767;
            this.TextYourName.MinimumSize = new System.Drawing.Size(100, 35);
            this.TextYourName.Modified = false;
            this.TextYourName.Multiline = false;
            this.TextYourName.Name = "TextYourName";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextYourName.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Empty;
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.Empty;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextYourName.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextYourName.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextYourName.OnIdleState = stateProperties4;
            this.TextYourName.PasswordChar = '\0';
            this.TextYourName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextYourName.PlaceholderText = "";
            this.TextYourName.ReadOnly = false;
            this.TextYourName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextYourName.SelectedText = "";
            this.TextYourName.SelectionLength = 0;
            this.TextYourName.SelectionStart = 0;
            this.TextYourName.ShortcutsEnabled = true;
            this.TextYourName.Size = new System.Drawing.Size(826, 35);
            this.TextYourName.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextYourName.TabIndex = 0;
            this.TextYourName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextYourName.TextMarginBottom = 0;
            this.TextYourName.TextMarginLeft = 5;
            this.TextYourName.TextMarginTop = 0;
            this.TextYourName.TextPlaceholder = "";
            this.TextYourName.UseSystemPasswordChar = false;
            this.TextYourName.WordWrap = true;
            // 
            // TextEmail
            // 
            this.TextEmail.AcceptsReturn = false;
            this.TextEmail.AcceptsTab = false;
            this.TextEmail.AnimationSpeed = 200;
            this.TextEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextEmail.BackColor = System.Drawing.Color.Transparent;
            this.TextEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextEmail.BackgroundImage")));
            this.TextEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextEmail.BorderRadius = 1;
            this.TextEmail.BorderThickness = 1;
            this.TextEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextEmail.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextEmail.DefaultText = "";
            this.TextEmail.FillColor = System.Drawing.Color.White;
            this.TextEmail.HideSelection = true;
            this.TextEmail.IconLeft = null;
            this.TextEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextEmail.IconPadding = 10;
            this.TextEmail.IconRight = null;
            this.TextEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextEmail.Lines = new string[0];
            this.TextEmail.Location = new System.Drawing.Point(27, 135);
            this.TextEmail.MaxLength = 32767;
            this.TextEmail.MinimumSize = new System.Drawing.Size(100, 35);
            this.TextEmail.Modified = false;
            this.TextEmail.Multiline = false;
            this.TextEmail.Name = "TextEmail";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextEmail.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Empty;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextEmail.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextEmail.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextEmail.OnIdleState = stateProperties8;
            this.TextEmail.PasswordChar = '\0';
            this.TextEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextEmail.PlaceholderText = "";
            this.TextEmail.ReadOnly = false;
            this.TextEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextEmail.SelectedText = "";
            this.TextEmail.SelectionLength = 0;
            this.TextEmail.SelectionStart = 0;
            this.TextEmail.ShortcutsEnabled = true;
            this.TextEmail.Size = new System.Drawing.Size(826, 35);
            this.TextEmail.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextEmail.TabIndex = 1;
            this.TextEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextEmail.TextMarginBottom = 0;
            this.TextEmail.TextMarginLeft = 5;
            this.TextEmail.TextMarginTop = 0;
            this.TextEmail.TextPlaceholder = "";
            this.TextEmail.UseSystemPasswordChar = false;
            this.TextEmail.WordWrap = true;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.label1.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.label1.Location = new System.Drawing.Point(27, 48);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(48, 17);
            this.label1.TabIndex = 233;
            this.label1.Text = "Nome:";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.label2.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.label2.Location = new System.Drawing.Point(27, 115);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(43, 17);
            this.label2.TabIndex = 234;
            this.label2.Text = "Email:";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.label3.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.label3.Location = new System.Drawing.Point(27, 182);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(44, 17);
            this.label3.TabIndex = 236;
            this.label3.Text = "Login:";
            // 
            // TextLogin
            // 
            this.TextLogin.AcceptsReturn = false;
            this.TextLogin.AcceptsTab = false;
            this.TextLogin.AnimationSpeed = 200;
            this.TextLogin.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextLogin.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextLogin.BackColor = System.Drawing.Color.Transparent;
            this.TextLogin.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextLogin.BackgroundImage")));
            this.TextLogin.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextLogin.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextLogin.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextLogin.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextLogin.BorderRadius = 1;
            this.TextLogin.BorderThickness = 1;
            this.TextLogin.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextLogin.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextLogin.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextLogin.DefaultText = "";
            this.TextLogin.FillColor = System.Drawing.Color.White;
            this.TextLogin.HideSelection = true;
            this.TextLogin.IconLeft = null;
            this.TextLogin.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextLogin.IconPadding = 10;
            this.TextLogin.IconRight = null;
            this.TextLogin.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextLogin.Lines = new string[0];
            this.TextLogin.Location = new System.Drawing.Point(27, 202);
            this.TextLogin.MaxLength = 32767;
            this.TextLogin.MinimumSize = new System.Drawing.Size(100, 35);
            this.TextLogin.Modified = false;
            this.TextLogin.Multiline = false;
            this.TextLogin.Name = "TextLogin";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextLogin.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Empty;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextLogin.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextLogin.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextLogin.OnIdleState = stateProperties12;
            this.TextLogin.PasswordChar = '\0';
            this.TextLogin.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextLogin.PlaceholderText = "";
            this.TextLogin.ReadOnly = false;
            this.TextLogin.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextLogin.SelectedText = "";
            this.TextLogin.SelectionLength = 0;
            this.TextLogin.SelectionStart = 0;
            this.TextLogin.ShortcutsEnabled = true;
            this.TextLogin.Size = new System.Drawing.Size(294, 35);
            this.TextLogin.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextLogin.TabIndex = 235;
            this.TextLogin.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextLogin.TextMarginBottom = 0;
            this.TextLogin.TextMarginLeft = 5;
            this.TextLogin.TextMarginTop = 0;
            this.TextLogin.TextPlaceholder = "";
            this.TextLogin.UseSystemPasswordChar = false;
            this.TextLogin.WordWrap = true;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.label4.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.label4.Location = new System.Drawing.Point(27, 249);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(113, 17);
            this.label4.TabIndex = 238;
            this.label4.Text = "Senha de Acesso:";
            // 
            // TextAccessPassWord
            // 
            this.TextAccessPassWord.AcceptsReturn = false;
            this.TextAccessPassWord.AcceptsTab = false;
            this.TextAccessPassWord.AnimationSpeed = 200;
            this.TextAccessPassWord.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextAccessPassWord.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextAccessPassWord.BackColor = System.Drawing.Color.Transparent;
            this.TextAccessPassWord.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextAccessPassWord.BackgroundImage")));
            this.TextAccessPassWord.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextAccessPassWord.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextAccessPassWord.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextAccessPassWord.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextAccessPassWord.BorderRadius = 1;
            this.TextAccessPassWord.BorderThickness = 1;
            this.TextAccessPassWord.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextAccessPassWord.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextAccessPassWord.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextAccessPassWord.DefaultText = "";
            this.TextAccessPassWord.FillColor = System.Drawing.Color.White;
            this.TextAccessPassWord.HideSelection = true;
            this.TextAccessPassWord.IconLeft = null;
            this.TextAccessPassWord.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextAccessPassWord.IconPadding = 10;
            this.TextAccessPassWord.IconRight = null;
            this.TextAccessPassWord.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextAccessPassWord.Lines = new string[0];
            this.TextAccessPassWord.Location = new System.Drawing.Point(27, 269);
            this.TextAccessPassWord.MaxLength = 32767;
            this.TextAccessPassWord.MinimumSize = new System.Drawing.Size(100, 35);
            this.TextAccessPassWord.Modified = false;
            this.TextAccessPassWord.Multiline = false;
            this.TextAccessPassWord.Name = "TextAccessPassWord";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextAccessPassWord.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Empty;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextAccessPassWord.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextAccessPassWord.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextAccessPassWord.OnIdleState = stateProperties16;
            this.TextAccessPassWord.PasswordChar = '*';
            this.TextAccessPassWord.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextAccessPassWord.PlaceholderText = "Enter text";
            this.TextAccessPassWord.ReadOnly = false;
            this.TextAccessPassWord.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextAccessPassWord.SelectedText = "";
            this.TextAccessPassWord.SelectionLength = 0;
            this.TextAccessPassWord.SelectionStart = 0;
            this.TextAccessPassWord.ShortcutsEnabled = true;
            this.TextAccessPassWord.Size = new System.Drawing.Size(292, 35);
            this.TextAccessPassWord.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextAccessPassWord.TabIndex = 237;
            this.TextAccessPassWord.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextAccessPassWord.TextMarginBottom = 0;
            this.TextAccessPassWord.TextMarginLeft = 5;
            this.TextAccessPassWord.TextMarginTop = 0;
            this.TextAccessPassWord.TextPlaceholder = "Enter text";
            this.TextAccessPassWord.UseSystemPasswordChar = false;
            this.TextAccessPassWord.WordWrap = true;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.label5.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.label5.Location = new System.Drawing.Point(27, 316);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(147, 17);
            this.label5.TabIndex = 240;
            this.label5.Text = "Confirmação da Senha:";
            // 
            // TextPassWordCheck
            // 
            this.TextPassWordCheck.AcceptsReturn = false;
            this.TextPassWordCheck.AcceptsTab = false;
            this.TextPassWordCheck.AnimationSpeed = 200;
            this.TextPassWordCheck.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextPassWordCheck.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextPassWordCheck.BackColor = System.Drawing.Color.Transparent;
            this.TextPassWordCheck.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextPassWordCheck.BackgroundImage")));
            this.TextPassWordCheck.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextPassWordCheck.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextPassWordCheck.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextPassWordCheck.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextPassWordCheck.BorderRadius = 1;
            this.TextPassWordCheck.BorderThickness = 1;
            this.TextPassWordCheck.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextPassWordCheck.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextPassWordCheck.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextPassWordCheck.DefaultText = "";
            this.TextPassWordCheck.FillColor = System.Drawing.Color.White;
            this.TextPassWordCheck.HideSelection = true;
            this.TextPassWordCheck.IconLeft = null;
            this.TextPassWordCheck.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextPassWordCheck.IconPadding = 10;
            this.TextPassWordCheck.IconRight = null;
            this.TextPassWordCheck.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextPassWordCheck.Lines = new string[0];
            this.TextPassWordCheck.Location = new System.Drawing.Point(27, 336);
            this.TextPassWordCheck.MaxLength = 32767;
            this.TextPassWordCheck.MinimumSize = new System.Drawing.Size(100, 35);
            this.TextPassWordCheck.Modified = false;
            this.TextPassWordCheck.Multiline = false;
            this.TextPassWordCheck.Name = "TextPassWordCheck";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextPassWordCheck.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Empty;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextPassWordCheck.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextPassWordCheck.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextPassWordCheck.OnIdleState = stateProperties20;
            this.TextPassWordCheck.PasswordChar = '*';
            this.TextPassWordCheck.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextPassWordCheck.PlaceholderText = "Enter text";
            this.TextPassWordCheck.ReadOnly = false;
            this.TextPassWordCheck.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextPassWordCheck.SelectedText = "";
            this.TextPassWordCheck.SelectionLength = 0;
            this.TextPassWordCheck.SelectionStart = 0;
            this.TextPassWordCheck.ShortcutsEnabled = true;
            this.TextPassWordCheck.Size = new System.Drawing.Size(292, 35);
            this.TextPassWordCheck.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextPassWordCheck.TabIndex = 239;
            this.TextPassWordCheck.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextPassWordCheck.TextMarginBottom = 0;
            this.TextPassWordCheck.TextMarginLeft = 5;
            this.TextPassWordCheck.TextMarginTop = 0;
            this.TextPassWordCheck.TextPlaceholder = "Enter text";
            this.TextPassWordCheck.UseSystemPasswordChar = false;
            this.TextPassWordCheck.WordWrap = true;
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.Gainsboro;
            this.bunifuShadowPanel1.Controls.Add(this.bunifuShadowPanel2);
            this.bunifuShadowPanel1.Controls.Add(this.TextPassWordCheck);
            this.bunifuShadowPanel1.Controls.Add(this.label5);
            this.bunifuShadowPanel1.Controls.Add(this.TextYourName);
            this.bunifuShadowPanel1.Controls.Add(this.TextEmail);
            this.bunifuShadowPanel1.Controls.Add(this.label4);
            this.bunifuShadowPanel1.Controls.Add(this.label1);
            this.bunifuShadowPanel1.Controls.Add(this.TextAccessPassWord);
            this.bunifuShadowPanel1.Controls.Add(this.label2);
            this.bunifuShadowPanel1.Controls.Add(this.label3);
            this.bunifuShadowPanel1.Controls.Add(this.TextLogin);
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(30, 67);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.Empty;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(882, 442);
            this.bunifuShadowPanel1.TabIndex = 241;
            // 
            // bunifuShadowPanel2
            // 
            this.bunifuShadowPanel2.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuShadowPanel2.BorderColor = System.Drawing.Color.Gainsboro;
            this.bunifuShadowPanel2.Controls.Add(this.ButtonClose);
            this.bunifuShadowPanel2.Controls.Add(this.ButtonClearView);
            this.bunifuShadowPanel2.Controls.Add(this.ButtonDelete);
            this.bunifuShadowPanel2.Controls.Add(this.ButtonSave);
            this.bunifuShadowPanel2.Location = new System.Drawing.Point(0, 448);
            this.bunifuShadowPanel2.Name = "bunifuShadowPanel2";
            this.bunifuShadowPanel2.PanelColor = System.Drawing.Color.Empty;
            this.bunifuShadowPanel2.ShadowDept = 2;
            this.bunifuShadowPanel2.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel2.Size = new System.Drawing.Size(882, 86);
            this.bunifuShadowPanel2.TabIndex = 245;
            // 
            // ButtonClose
            // 
            this.ButtonClose.AllowToggling = false;
            this.ButtonClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.ButtonClose.AnimationSpeed = 200;
            this.ButtonClose.AutoGenerateColors = false;
            this.ButtonClose.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this.ButtonClose.BackColor = System.Drawing.Color.Transparent;
            this.ButtonClose.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.ButtonClose.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ButtonClose.BackgroundImage")));
            this.ButtonClose.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonClose.ButtonText = "Sair";
            this.ButtonClose.ButtonTextMarginLeft = 0;
            this.ButtonClose.ColorContrastOnClick = 45;
            this.ButtonClose.ColorContrastOnHover = 45;
            this.ButtonClose.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.ButtonClose.CustomizableEdges = borderEdges1;
            this.ButtonClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ButtonClose.DisabledBorderColor = System.Drawing.Color.Empty;
            this.ButtonClose.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ButtonClose.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ButtonClose.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ButtonClose.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.ButtonClose.ForeColor = System.Drawing.Color.White;
            this.ButtonClose.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonClose.IconMarginLeft = 11;
            this.ButtonClose.IconPadding = 10;
            this.ButtonClose.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonClose.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.ButtonClose.IdleBorderRadius = 3;
            this.ButtonClose.IdleBorderThickness = 1;
            this.ButtonClose.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.ButtonClose.IdleIconLeftImage = null;
            this.ButtonClose.IdleIconRightImage = null;
            this.ButtonClose.IndicateFocus = false;
            this.ButtonClose.Location = new System.Drawing.Point(712, 22);
            this.ButtonClose.Name = "ButtonClose";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties21.BorderRadius = 3;
            stateProperties21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties21.BorderThickness = 1;
            stateProperties21.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties21.ForeColor = System.Drawing.Color.White;
            stateProperties21.IconLeftImage = null;
            stateProperties21.IconRightImage = null;
            this.ButtonClose.onHoverState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            stateProperties22.BorderRadius = 3;
            stateProperties22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties22.BorderThickness = 1;
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            stateProperties22.ForeColor = System.Drawing.Color.White;
            stateProperties22.IconLeftImage = null;
            stateProperties22.IconRightImage = null;
            this.ButtonClose.OnPressedState = stateProperties22;
            this.ButtonClose.Size = new System.Drawing.Size(144, 45);
            this.ButtonClose.TabIndex = 14;
            this.ButtonClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ButtonClose.TextMarginLeft = 0;
            this.ButtonClose.UseDefaultRadiusAndThickness = true;
            // 
            // ButtonClearView
            // 
            this.ButtonClearView.AllowToggling = false;
            this.ButtonClearView.AnimationSpeed = 200;
            this.ButtonClearView.AutoGenerateColors = false;
            this.ButtonClearView.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this.ButtonClearView.BackColor = System.Drawing.Color.Transparent;
            this.ButtonClearView.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.ButtonClearView.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ButtonClearView.BackgroundImage")));
            this.ButtonClearView.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonClearView.ButtonText = "Limpar Formulário";
            this.ButtonClearView.ButtonTextMarginLeft = 0;
            this.ButtonClearView.ColorContrastOnClick = 45;
            this.ButtonClearView.ColorContrastOnHover = 45;
            this.ButtonClearView.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.ButtonClearView.CustomizableEdges = borderEdges2;
            this.ButtonClearView.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ButtonClearView.DisabledBorderColor = System.Drawing.Color.Empty;
            this.ButtonClearView.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ButtonClearView.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ButtonClearView.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ButtonClearView.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.ButtonClearView.ForeColor = System.Drawing.Color.White;
            this.ButtonClearView.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonClearView.IconMarginLeft = 11;
            this.ButtonClearView.IconPadding = 10;
            this.ButtonClearView.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonClearView.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.ButtonClearView.IdleBorderRadius = 3;
            this.ButtonClearView.IdleBorderThickness = 1;
            this.ButtonClearView.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.ButtonClearView.IdleIconLeftImage = null;
            this.ButtonClearView.IdleIconRightImage = null;
            this.ButtonClearView.IndicateFocus = false;
            this.ButtonClearView.Location = new System.Drawing.Point(330, 22);
            this.ButtonClearView.Name = "ButtonClearView";
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.BorderRadius = 3;
            stateProperties23.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties23.BorderThickness = 1;
            stateProperties23.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.ForeColor = System.Drawing.Color.White;
            stateProperties23.IconLeftImage = null;
            stateProperties23.IconRightImage = null;
            this.ButtonClearView.onHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            stateProperties24.BorderRadius = 3;
            stateProperties24.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties24.BorderThickness = 1;
            stateProperties24.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            stateProperties24.ForeColor = System.Drawing.Color.White;
            stateProperties24.IconLeftImage = null;
            stateProperties24.IconRightImage = null;
            this.ButtonClearView.OnPressedState = stateProperties24;
            this.ButtonClearView.Size = new System.Drawing.Size(144, 45);
            this.ButtonClearView.TabIndex = 13;
            this.ButtonClearView.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ButtonClearView.TextMarginLeft = 0;
            this.ButtonClearView.UseDefaultRadiusAndThickness = true;
            // 
            // ButtonDelete
            // 
            this.ButtonDelete.AllowToggling = false;
            this.ButtonDelete.AnimationSpeed = 200;
            this.ButtonDelete.AutoGenerateColors = false;
            this.ButtonDelete.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this.ButtonDelete.BackColor = System.Drawing.Color.Transparent;
            this.ButtonDelete.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.ButtonDelete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ButtonDelete.BackgroundImage")));
            this.ButtonDelete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonDelete.ButtonText = "Excluir Dados";
            this.ButtonDelete.ButtonTextMarginLeft = 0;
            this.ButtonDelete.ColorContrastOnClick = 45;
            this.ButtonDelete.ColorContrastOnHover = 45;
            this.ButtonDelete.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.ButtonDelete.CustomizableEdges = borderEdges3;
            this.ButtonDelete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ButtonDelete.DisabledBorderColor = System.Drawing.Color.Empty;
            this.ButtonDelete.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ButtonDelete.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ButtonDelete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ButtonDelete.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.ButtonDelete.ForeColor = System.Drawing.Color.White;
            this.ButtonDelete.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonDelete.IconMarginLeft = 11;
            this.ButtonDelete.IconPadding = 10;
            this.ButtonDelete.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonDelete.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.ButtonDelete.IdleBorderRadius = 3;
            this.ButtonDelete.IdleBorderThickness = 1;
            this.ButtonDelete.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.ButtonDelete.IdleIconLeftImage = null;
            this.ButtonDelete.IdleIconRightImage = null;
            this.ButtonDelete.IndicateFocus = false;
            this.ButtonDelete.Location = new System.Drawing.Point(180, 22);
            this.ButtonDelete.Name = "ButtonDelete";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties25.BorderRadius = 3;
            stateProperties25.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties25.BorderThickness = 1;
            stateProperties25.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties25.ForeColor = System.Drawing.Color.White;
            stateProperties25.IconLeftImage = null;
            stateProperties25.IconRightImage = null;
            this.ButtonDelete.onHoverState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            stateProperties26.BorderRadius = 3;
            stateProperties26.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties26.BorderThickness = 1;
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            stateProperties26.ForeColor = System.Drawing.Color.White;
            stateProperties26.IconLeftImage = null;
            stateProperties26.IconRightImage = null;
            this.ButtonDelete.OnPressedState = stateProperties26;
            this.ButtonDelete.Size = new System.Drawing.Size(144, 45);
            this.ButtonDelete.TabIndex = 12;
            this.ButtonDelete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ButtonDelete.TextMarginLeft = 0;
            this.ButtonDelete.UseDefaultRadiusAndThickness = true;
            // 
            // ButtonSave
            // 
            this.ButtonSave.AllowToggling = false;
            this.ButtonSave.AnimationSpeed = 200;
            this.ButtonSave.AutoGenerateColors = false;
            this.ButtonSave.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this.ButtonSave.BackColor = System.Drawing.Color.Transparent;
            this.ButtonSave.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.ButtonSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ButtonSave.BackgroundImage")));
            this.ButtonSave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonSave.ButtonText = "Salvar Dados";
            this.ButtonSave.ButtonTextMarginLeft = 0;
            this.ButtonSave.ColorContrastOnClick = 45;
            this.ButtonSave.ColorContrastOnHover = 45;
            this.ButtonSave.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.ButtonSave.CustomizableEdges = borderEdges4;
            this.ButtonSave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ButtonSave.DisabledBorderColor = System.Drawing.Color.Empty;
            this.ButtonSave.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ButtonSave.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ButtonSave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ButtonSave.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.ButtonSave.ForeColor = System.Drawing.Color.White;
            this.ButtonSave.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonSave.IconMarginLeft = 11;
            this.ButtonSave.IconPadding = 10;
            this.ButtonSave.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonSave.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.ButtonSave.IdleBorderRadius = 3;
            this.ButtonSave.IdleBorderThickness = 1;
            this.ButtonSave.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.ButtonSave.IdleIconLeftImage = null;
            this.ButtonSave.IdleIconRightImage = null;
            this.ButtonSave.IndicateFocus = false;
            this.ButtonSave.Location = new System.Drawing.Point(30, 22);
            this.ButtonSave.Name = "ButtonSave";
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.BorderRadius = 3;
            stateProperties27.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties27.BorderThickness = 1;
            stateProperties27.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.ForeColor = System.Drawing.Color.White;
            stateProperties27.IconLeftImage = null;
            stateProperties27.IconRightImage = null;
            this.ButtonSave.onHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            stateProperties28.BorderRadius = 3;
            stateProperties28.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties28.BorderThickness = 1;
            stateProperties28.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            stateProperties28.ForeColor = System.Drawing.Color.White;
            stateProperties28.IconLeftImage = null;
            stateProperties28.IconRightImage = null;
            this.ButtonSave.OnPressedState = stateProperties28;
            this.ButtonSave.Size = new System.Drawing.Size(144, 45);
            this.ButtonSave.TabIndex = 11;
            this.ButtonSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ButtonSave.TextMarginLeft = 0;
            this.ButtonSave.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuShadowPanel3
            // 
            this.bunifuShadowPanel3.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuShadowPanel3.BorderColor = System.Drawing.Color.Gainsboro;
            this.bunifuShadowPanel3.Controls.Add(this.bunifuButton1);
            this.bunifuShadowPanel3.Controls.Add(this.bunifuButton2);
            this.bunifuShadowPanel3.Controls.Add(this.bunifuButton3);
            this.bunifuShadowPanel3.Controls.Add(this.bunifuButton4);
            this.bunifuShadowPanel3.Location = new System.Drawing.Point(30, 518);
            this.bunifuShadowPanel3.Name = "bunifuShadowPanel3";
            this.bunifuShadowPanel3.PanelColor = System.Drawing.Color.Empty;
            this.bunifuShadowPanel3.ShadowDept = 2;
            this.bunifuShadowPanel3.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel3.Size = new System.Drawing.Size(882, 86);
            this.bunifuShadowPanel3.TabIndex = 245;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Sair";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges5;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.bunifuButton1.IdleBorderRadius = 3;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(709, 19);
            this.bunifuButton1.Name = "bunifuButton1";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties29.BorderRadius = 3;
            stateProperties29.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties29.BorderThickness = 1;
            stateProperties29.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties29.ForeColor = System.Drawing.Color.White;
            stateProperties29.IconLeftImage = null;
            stateProperties29.IconRightImage = null;
            this.bunifuButton1.onHoverState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            stateProperties30.BorderRadius = 3;
            stateProperties30.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties30.BorderThickness = 1;
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            stateProperties30.ForeColor = System.Drawing.Color.White;
            stateProperties30.IconLeftImage = null;
            stateProperties30.IconRightImage = null;
            this.bunifuButton1.OnPressedState = stateProperties30;
            this.bunifuButton1.Size = new System.Drawing.Size(144, 45);
            this.bunifuButton1.TabIndex = 14;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "Limpar Formulário";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges6;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.bunifuButton2.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.bunifuButton2.IdleBorderRadius = 3;
            this.bunifuButton2.IdleBorderThickness = 1;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(327, 19);
            this.bunifuButton2.Name = "bunifuButton2";
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.BorderRadius = 3;
            stateProperties31.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties31.BorderThickness = 1;
            stateProperties31.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.ForeColor = System.Drawing.Color.White;
            stateProperties31.IconLeftImage = null;
            stateProperties31.IconRightImage = null;
            this.bunifuButton2.onHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            stateProperties32.BorderRadius = 3;
            stateProperties32.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties32.BorderThickness = 1;
            stateProperties32.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            stateProperties32.ForeColor = System.Drawing.Color.White;
            stateProperties32.IconLeftImage = null;
            stateProperties32.IconRightImage = null;
            this.bunifuButton2.OnPressedState = stateProperties32;
            this.bunifuButton2.Size = new System.Drawing.Size(144, 45);
            this.bunifuButton2.TabIndex = 13;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton3
            // 
            this.bunifuButton3.AllowToggling = false;
            this.bunifuButton3.AnimationSpeed = 200;
            this.bunifuButton3.AutoGenerateColors = false;
            this.bunifuButton3.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this.bunifuButton3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.bunifuButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.BackgroundImage")));
            this.bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.ButtonText = "Excluir Dados";
            this.bunifuButton3.ButtonTextMarginLeft = 0;
            this.bunifuButton3.ColorContrastOnClick = 45;
            this.bunifuButton3.ColorContrastOnHover = 45;
            this.bunifuButton3.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.bunifuButton3.CustomizableEdges = borderEdges7;
            this.bunifuButton3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton3.DisabledBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.bunifuButton3.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton3.IconMarginLeft = 11;
            this.bunifuButton3.IconPadding = 10;
            this.bunifuButton3.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton3.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.bunifuButton3.IdleBorderRadius = 3;
            this.bunifuButton3.IdleBorderThickness = 1;
            this.bunifuButton3.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.bunifuButton3.IdleIconLeftImage = null;
            this.bunifuButton3.IdleIconRightImage = null;
            this.bunifuButton3.IndicateFocus = false;
            this.bunifuButton3.Location = new System.Drawing.Point(177, 19);
            this.bunifuButton3.Name = "bunifuButton3";
            stateProperties33.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties33.BorderRadius = 3;
            stateProperties33.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties33.BorderThickness = 1;
            stateProperties33.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties33.ForeColor = System.Drawing.Color.White;
            stateProperties33.IconLeftImage = null;
            stateProperties33.IconRightImage = null;
            this.bunifuButton3.onHoverState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            stateProperties34.BorderRadius = 3;
            stateProperties34.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties34.BorderThickness = 1;
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            stateProperties34.ForeColor = System.Drawing.Color.White;
            stateProperties34.IconLeftImage = null;
            stateProperties34.IconRightImage = null;
            this.bunifuButton3.OnPressedState = stateProperties34;
            this.bunifuButton3.Size = new System.Drawing.Size(144, 45);
            this.bunifuButton3.TabIndex = 12;
            this.bunifuButton3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton3.TextMarginLeft = 0;
            this.bunifuButton3.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton4
            // 
            this.bunifuButton4.AllowToggling = false;
            this.bunifuButton4.AnimationSpeed = 200;
            this.bunifuButton4.AutoGenerateColors = false;
            this.bunifuButton4.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this.bunifuButton4.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton4.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.bunifuButton4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton4.BackgroundImage")));
            this.bunifuButton4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.ButtonText = "Salvar Dados";
            this.bunifuButton4.ButtonTextMarginLeft = 0;
            this.bunifuButton4.ColorContrastOnClick = 45;
            this.bunifuButton4.ColorContrastOnHover = 45;
            this.bunifuButton4.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.bunifuButton4.CustomizableEdges = borderEdges8;
            this.bunifuButton4.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton4.DisabledBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton4.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton4.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton4.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton4.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.bunifuButton4.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton4.IconMarginLeft = 11;
            this.bunifuButton4.IconPadding = 10;
            this.bunifuButton4.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton4.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.bunifuButton4.IdleBorderRadius = 3;
            this.bunifuButton4.IdleBorderThickness = 1;
            this.bunifuButton4.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            this.bunifuButton4.IdleIconLeftImage = null;
            this.bunifuButton4.IdleIconRightImage = null;
            this.bunifuButton4.IndicateFocus = false;
            this.bunifuButton4.Location = new System.Drawing.Point(27, 19);
            this.bunifuButton4.Name = "bunifuButton4";
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.BorderRadius = 3;
            stateProperties35.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties35.BorderThickness = 1;
            stateProperties35.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.ForeColor = System.Drawing.Color.White;
            stateProperties35.IconLeftImage = null;
            stateProperties35.IconRightImage = null;
            this.bunifuButton4.onHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            stateProperties36.BorderRadius = 3;
            stateProperties36.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties36.BorderThickness = 1;
            stateProperties36.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(156)))), ((int)(((byte)(229)))));
            stateProperties36.ForeColor = System.Drawing.Color.White;
            stateProperties36.IconLeftImage = null;
            stateProperties36.IconRightImage = null;
            this.bunifuButton4.OnPressedState = stateProperties36;
            this.bunifuButton4.Size = new System.Drawing.Size(144, 45);
            this.bunifuButton4.TabIndex = 11;
            this.bunifuButton4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton4.TextMarginLeft = 0;
            this.bunifuButton4.UseDefaultRadiusAndThickness = true;
            // 
            // UserLoginAddScreen
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(944, 649);
            this.Controls.Add(this.bunifuShadowPanel3);
            this.Controls.Add(this.bunifuShadowPanel1);
            this.MinimumSize = new System.Drawing.Size(944, 590);
            this.Name = "UserLoginAddScreen";
            this.Text = "Cadastro de Usuários";
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            this.bunifuShadowPanel2.ResumeLayout(false);
            this.bunifuShadowPanel3.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextYourName;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextEmail;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextLogin;
        private System.Windows.Forms.Label label4;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextAccessPassWord;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextPassWordCheck;
        private Bunifu.UI.WinForm.BunifuShadowPanel.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForm.BunifuShadowPanel.BunifuShadowPanel bunifuShadowPanel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ButtonClose;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ButtonClearView;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ButtonDelete;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ButtonSave;
        private Bunifu.UI.WinForm.BunifuShadowPanel.BunifuShadowPanel bunifuShadowPanel3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton4;
    }
}